services:
  node:
    build: ./
    image: taxi-backend
    ports:
      - 8080:8080
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - db
    env_file:
      - ./.env
    networks:
      - app-taxi

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    networks:
      - app-taxi
      
networks:
  app-taxi:
    driver: bridge